server:
  port: 2000
spring:
  application:
    name: zuul-server
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        #server-addr: ${NACOS_HOST:sfa-register}:${NACOS_PORT:8848}
        namespace: public
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${NAMESPACE:dev}
  config:
    import:
      - optional:nacos:application-${spring.cloud.nacos.config.namespace}.yml
      - optional:nacos:${spring.application.name}-${spring.cloud.nacos.config.namespace}.yml

zuul:
  ignored-services: "*"  #禁止使用服务名字进行访问
  prefix: "/servers" #统一的前缀
  routes: #配置路由，指定服务的访问路径
    resource1-server: "/resources/**"