server:
  port: 2000
spring:
  application:
    name: self-auth
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 104.168.123.154 # 地址
    port: 6379 # 端口
    database: 0 # 数据库索引
  security:
    user:
      name: yyg
      password: 123
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        #server-addr: ${NACOS_HOST:sfa-register}:${NACOS_PORT:8848}
        namespace: 7ac2d503-a1a2-4099-b6c3-92d06ad1a3e6
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${NAMESPACE:dev}
  config:
    import:
      - optional:nacos:application-${spring.cloud.nacos.config.namespace}.yml
      - optional:nacos:${spring.application.name}-dev.yml