server:
  port: 4000
  servlet:
    context-path: /org
spring:
  application:
    name: self-org
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        #server-addr: ${NACOS_HOST:sfa-register}:${NACOS_PORT:8848}
        namespace: 99ee4cc1-6b73-4715-b9bf-c0225bc109d4
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${NAMESPACE:99ee4cc1-6b73-4715-b9bf-c0225bc109d4}
  config:
    import:
      - optional:nacos:application-${spring.cloud.nacos.config.namespace}.yml
      - optional:nacos:${spring.application.name}-dev.yml